apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: manager-role
rules:
  - apiGroups:
      - connectors.cloud.yandex.com
    resources:
      - yandexobjectstorages
    verbs:
      - create
      - delete
      - get
      - list
      - patch
      - update
      - watch
  - apiGroups:
      - connectors.cloud.yandex.com
    resources:
      - yandexobjectstorages/finalizers
    verbs:
      - update
  - apiGroups:
      - connectors.cloud.yandex.com
    resources:
      - yandexobjectstorages/status
    verbs:
      - get
      - patch
      - update
  - apiGroups:
      - connectors.cloud.yandex.com
    resources:
      - staticaccesskeys
    verbs:
      - get
  - apiGroups:
      - connectors.cloud.yandex.com
    resources:
      - staticaccesskeys/status
    verbs:
      - get
  - apiGroups:
      - ""
    resources:
      - secrets
    verbs:
      - get