apiVersion: v1
kind: Service
metadata:
  name: webhook-service
  namespace: yandex-cloud-connectors
spec:
  selector:
    control-plane: connector-manager
  ports:
    - port: 443
      targetPort: 9443
      protocol: TCP