apiVersion: v1
kind: Namespace
metadata:
  name: yandex-cloud-connectors-example

---

apiVersion: connectors.cloud.yandex.com/v1
kind: StaticAccessKey
metadata:
  namespace: yandex-cloud-connectors-example
  name: example-sakey
spec:
  serviceAccountId: ajev6g6albed8vl7ja82

---

apiVersion: connectors.cloud.yandex.com/v1
kind: YandexObjectStorage
metadata:
  namespace: yandex-cloud-connectors-example
  name: example-object-storage
spec:
  name: ycc-example-object-storage
  SAKeyName: example-sakey

---

apiVersion: connectors.cloud.yandex.com/v1
kind: YandexMessageQueue
metadata:
  namespace: yandex-cloud-connectors-example
  name: example-message-queue
spec:
  name: ycc-example-message-queue
  SAKeyName: example-sakey

---

apiVersion: connectors.cloud.yandex.com/v1
kind: YandexContainerRegistry
metadata:
  namespace: yandex-cloud-connectors-example
  name: example-registry
spec:
  folderId: b1g7jvgmf06eel94s22d
  name: ycc-example-registry
