apiVersion: apps/v1
kind: Deployment
metadata:
  name: connector-manager
  namespace: {{ .Values.namespace }}
  labels:
    control-plane: connector-manager
spec:
  selector:
    matchLabels:
      control-plane: connector-manager
  replicas: 1
  template:
    metadata:
      labels:
        control-plane: connector-manager
    spec:
      securityContext:
        runAsNonRoot: true
      containers:
        - image: {{ .Values.imageRegistry }}/yc-connector-manager:{{ .Values.imageTag }}
          args:
            {{ if .Values.debug }}- --debug{{ end }}
          name: manager
          securityContext:
            allowPrivilegeEscalation: false
          livenessProbe:
            httpGet:
              path: /healthz
              port: 8081
            initialDelaySeconds: 15
            periodSeconds: 20
          readinessProbe:
            httpGet:
              path: /readyz
              port: 8081
            initialDelaySeconds: 5
            periodSeconds: 10
          ports:
            - containerPort: 9443
              name: webhook-server
              protocol: TCP
          resources:
            limits:
              cpu: 100m
              memory: 30Mi
            requests:
              cpu: 100m
              memory: 20Mi
          volumeMounts:
            - mountPath: /etc/yandex-cloud-connectors/certs
              name: tls-certificate
              readOnly: true
      volumes:
        - name: tls-certificate
          secret:
            secretName: webhook-tls-cert
      terminationGracePeriodSeconds: 10
