apiVersion: batch/v1
kind: Job
metadata:
  namespace: {{ .Values.namespace }}
  name: initial-certifier
spec:
  template:
    spec:
      restartPolicy: OnFailure
      containers:
        - name: certifier
          image: {{ .Values.imageRegistry }}/certifier:{{ .Chart.AppVersion }}
          args:
            {{ if .Values.debug }}- --debug{{ end }}
            - --namespace={{ .Values.namespace }}
            - --service=webhook-service
            - --secret=webhook-tls-cert
            - --vw=validating-webhook-configuration