apiVersion: v1
kind: Secret
metadata:
  name: connector-sakey-secret
  namespace: {{ .Values.namespace }}
stringData:
  key: |
{{ required "saKey value is required to be set on install" .Values.saKey | indent 4}}
