apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - manifests.yaml
  - service.yaml
patchesJson6902:
  - target:
      kind: MutatingWebhookConfiguration
      name: mutating-webhook-configuration
      version: v1
    path: patch.yaml
  - target:
      kind: ValidatingWebhookConfiguration
      name: validating-webhook-configuration
      version: v1
    path: patch.yaml