# This patch changes service namespaces of webhook configurations
- op: replace
  path: /webhooks/0/clientConfig/service/namespace
  value: yandex-cloud-connectors
- op: add
  path: /webhooks/0/clientConfig/caBundle
  value: |
    IA==

- op: replace
  path: /webhooks/1/clientConfig/service/namespace
  value: yandex-cloud-connectors
- op: add
  path: /webhooks/1/clientConfig/caBundle
  value: |
    IA==

- op: replace
  path: /webhooks/2/clientConfig/service/namespace
  value: yandex-cloud-connectors
- op: add
  path: /webhooks/2/clientConfig/caBundle
  value: |
    IA==

- op: replace
  path: /webhooks/3/clientConfig/service/namespace
  value: yandex-cloud-connectors
- op: add
  path: /webhooks/3/clientConfig/caBundle
  value: |
    IA==
