apiVersion: connectors.cloud.yandex.com/v1
kind: YandexObjectStorage
metadata:
  name: test-s3-2
spec:
  name: test-s3-1
  size: 10
  listingAccess: public
  readAccess: public
  configAccess: public
  storageType: cold
  SAKeyRef: test-key-1
