# permissions for end users to edit yandexobjectstorages.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: yandexobjectstorage-editor-role
rules:
- apiGroups:
  - connectors.cloud.yandex.ru
  resources:
  - yandexobjectstorages
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - connectors.cloud.yandex.ru
  resources:
  - yandexobjectstorages/status
  verbs:
  - get
