apiVersion: v1
kind: Service
metadata:
  name: image-reporter
  namespace: yandex-cloud-connectors-example
spec:
  type: LoadBalancer
  selector:
    control-plane: server
  ports:
    - port: 80
      targetPort: 8080
      protocol: TCP