apiVersion: batch/v1beta1
kind: CronJob
metadata:
  namespace: yandex-cloud-connectors
  name: cron-certifier
spec:
  # This is for running twice a year, on 29th of April and 29th of October
  schedule: 0 0 29 4,10 *
  jobTemplate:
    spec:
      template:
        spec:
          restartPolicy: OnFailure
          containers:
            - name: certifier
              image: cr.yandex/crptp7j81e7caog8r6gq/yc-connector-certifier:latest
              args:
                - --namespace=yandex-cloud-connectors
                - --service=webhook-service
                - --secret=webhook-tls-cert
                - --mw=mutating-webhook-configuration
                - --vw=validating-webhook-configuration