apiVersion: apps/v1
kind: Deployment
metadata:
  name: connector-manager
  namespace: yandex-cloud-connectors
spec:
  selector:
    matchLabels:
      control-plane: connector-manager
  replicas: 1
  template:
    metadata:
      labels:
        control-plane: connector-manager
    spec:
      securityContext:
        runAsNonRoot: true
      containers:
        - image: cr.yandex/crptp7j81e7caog8r6gq/yc-connector-manager:latest
          name: manager
          securityContext:
            allowPrivilegeEscalation: false
          livenessProbe:
            httpGet:
              path: /healthz
              port: 8081
            initialDelaySeconds: 15
            periodSeconds: 20
          readinessProbe:
            httpGet:
              path: /readyz
              port: 8081
            initialDelaySeconds: 5
            periodSeconds: 10
          resources:
            limits:
              cpu: 100m
              memory: 30Mi
            requests:
              cpu: 100m
              memory: 20Mi
      terminationGracePeriodSeconds: 10
