apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: connector-manager-rolebinding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: connector-manager-role
subjects:
  - kind: ServiceAccount
    namespace: yandex-cloud-connectors
    name: default
