# permissions for end users to edit yandexcontainerregistries.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: yandexcontainerregistry-editor-role
rules:
- apiGroups:
  - connectors.cloud.yandex.com
  resources:
  - yandexcontainerregistries
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - connectors.cloud.yandex.com
  resources:
  - yandexcontainerregistries/status
  verbs:
  - get
